# fly.toml app configuration file generated for email-whatsapp on 2025-08-04T18:19:52-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'email-whatsapp'
primary_region = 'gru'

[build]

[[vm]]
  size = 'shared-cpu-1x'
